/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: pkg/pbtypes/string.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../gogoproto/gogo";
import * as pb_1 from "google-protobuf";
export namespace pbtypes {
    export class String extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            Value?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("Value" in data && data.Value != undefined) {
                    this.Value = data.Value;
                }
            }
        }
        get Value() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set Value(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            Value?: string;
        }): String {
            const message = new String({});
            if (data.Value != null) {
                message.Value = data.Value;
            }
            return message;
        }
        toObject() {
            const data: {
                Value?: string;
            } = {};
            if (this.Value != null) {
                data.Value = this.Value;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.Value.length)
                writer.writeString(1, this.Value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): String {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new String();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.Value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): String {
            return String.deserialize(bytes);
        }
    }
}
