version: '3.8'
services:

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: trax_postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
