// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cmd/auth/grpc/auth.proto

package grpc

import (
	context "context"
	fmt "fmt"
	dto "github.com/elojah/trax/internal/user/dto"
	_ "github.com/elojah/trax/pkg/gogoproto"
	pbtypes "github.com/elojah/trax/pkg/pbtypes"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("cmd/auth/grpc/auth.proto", fileDescriptor_8ff23c0b7b7bec20) }
func init() { golang_proto.RegisterFile("cmd/auth/grpc/auth.proto", fileDescriptor_8ff23c0b7b7bec20) }

var fileDescriptor_8ff23c0b7b7bec20 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0x7d, 0xa5, 0xaa, 0x43, 0xf4, 0xab, 0x95, 0xbc, 0xfc, 0x55, 0x85, 0xee, 0x84, 0x10,
	0x2c, 0x31, 0x82, 0x27, 0x00, 0x09, 0xb1, 0xa2, 0x96, 0x89, 0x2d, 0x6d, 0x8d, 0x63, 0xda, 0xda,
	0xc6, 0x71, 0x24, 0xba, 0xf1, 0x08, 0x3c, 0x06, 0x8f, 0xc0, 0xd8, 0xb1, 0x63, 0xc7, 0x8e, 0xc4,
	0x19, 0x60, 0xec, 0xc8, 0x88, 0xe2, 0x54, 0xa8, 0xad, 0x18, 0xd8, 0xce, 0xb9, 0xdf, 0xb9, 0x37,
	0x47, 0x71, 0xd4, 0x19, 0x4e, 0x47, 0x2c, 0xc9, 0x5d, 0xca, 0x84, 0x35, 0xc3, 0xa0, 0x62, 0x63,
	0xb5, 0xd3, 0xb4, 0x51, 0x0d, 0xba, 0x1d, 0x33, 0x16, 0x4c, 0x68, 0xa1, 0xc3, 0x30, 0xa8, 0x9a,
	0x77, 0xff, 0x57, 0xc4, 0x0c, 0xdc, 0xcc, 0xf0, 0x8c, 0xf1, 0xa9, 0x71, 0xb3, 0x0d, 0xe8, 0x6c,
	0x83, 0xcc, 0x59, 0xa9, 0xc4, 0x86, 0x1c, 0x48, 0xe5, 0xb8, 0x55, 0xc9, 0x84, 0xe5, 0x19, 0xb7,
	0x6c, 0xe4, 0x74, 0x10, 0x35, 0x3d, 0xfb, 0x80, 0xa8, 0x71, 0x91, 0xbb, 0x94, 0x1e, 0x47, 0xcd,
	0xbe, 0x14, 0x2a, 0x37, 0xb4, 0x15, 0x8f, 0x9c, 0x8e, 0x6b, 0xd3, 0xe3, 0x8f, 0xdd, 0x56, 0xbc,
	0xb9, 0x1b, 0x5f, 0x55, 0x1f, 0xa4, 0x27, 0x75, 0x52, 0xaa, 0xad, 0xa4, 0x54, 0x55, 0xb2, 0xbd,
	0xe3, 0x33, 0x43, 0x4f, 0xa3, 0x7f, 0xb5, 0xbb, 0xd6, 0x5a, 0x4c, 0x38, 0x6d, 0xff, 0x9c, 0xea,
	0x87, 0x8a, 0xbf, 0x6e, 0xf4, 0xf8, 0xbd, 0xe5, 0x59, 0x7a, 0xab, 0xc7, 0x5c, 0xfd, 0x61, 0xe3,
	0x28, 0x6a, 0xdc, 0x48, 0x25, 0xe8, 0x5e, 0xcd, 0xfd, 0xda, 0x97, 0x6a, 0x51, 0x20, 0x59, 0x16,
	0x48, 0x56, 0x05, 0x92, 0x75, 0x81, 0xf0, 0x55, 0x20, 0x3c, 0x7b, 0x84, 0x57, 0x8f, 0xf0, 0xe6,
	0x11, 0xe6, 0x1e, 0x61, 0xe1, 0x11, 0x96, 0x1e, 0xe1, 0xdd, 0x23, 0x7c, 0x7a, 0x24, 0x6b, 0x8f,
	0xf0, 0x52, 0x22, 0x99, 0x97, 0x08, 0xcb, 0x12, 0xc9, 0xaa, 0x44, 0x72, 0x77, 0x28, 0xa4, 0x4b,
	0xf3, 0x41, 0x3c, 0xd4, 0x53, 0xc6, 0x27, 0xfa, 0x21, 0x49, 0x99, 0xb3, 0xc9, 0x13, 0xdb, 0x79,
	0xd5, 0x41, 0x33, 0xfc, 0xe0, 0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x49, 0x30, 0xff,
	0xed, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// Signup
	Signup(ctx context.Context, in *dto.SignupReq, opts ...grpc.CallOption) (*pbtypes.Empty, error)
	// Signin
	Signin(ctx context.Context, in *dto.SigninReq, opts ...grpc.CallOption) (*dto.SigninResp, error)
	// Signin Google
	SigninGoogle(ctx context.Context, in *pbtypes.String, opts ...grpc.CallOption) (*dto.SigninResp, error)
	// Refresh token
	RefreshToken(ctx context.Context, in *pbtypes.String, opts ...grpc.CallOption) (*dto.SigninResp, error)
	// Ping
	Ping(ctx context.Context, in *pbtypes.Empty, opts ...grpc.CallOption) (*pbtypes.Empty, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Signup(ctx context.Context, in *dto.SignupReq, opts ...grpc.CallOption) (*pbtypes.Empty, error) {
	out := new(pbtypes.Empty)
	err := c.cc.Invoke(ctx, "/grpc.Auth/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Signin(ctx context.Context, in *dto.SigninReq, opts ...grpc.CallOption) (*dto.SigninResp, error) {
	out := new(dto.SigninResp)
	err := c.cc.Invoke(ctx, "/grpc.Auth/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SigninGoogle(ctx context.Context, in *pbtypes.String, opts ...grpc.CallOption) (*dto.SigninResp, error) {
	out := new(dto.SigninResp)
	err := c.cc.Invoke(ctx, "/grpc.Auth/SigninGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshToken(ctx context.Context, in *pbtypes.String, opts ...grpc.CallOption) (*dto.SigninResp, error) {
	out := new(dto.SigninResp)
	err := c.cc.Invoke(ctx, "/grpc.Auth/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Ping(ctx context.Context, in *pbtypes.Empty, opts ...grpc.CallOption) (*pbtypes.Empty, error) {
	out := new(pbtypes.Empty)
	err := c.cc.Invoke(ctx, "/grpc.Auth/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// Signup
	Signup(context.Context, *dto.SignupReq) (*pbtypes.Empty, error)
	// Signin
	Signin(context.Context, *dto.SigninReq) (*dto.SigninResp, error)
	// Signin Google
	SigninGoogle(context.Context, *pbtypes.String) (*dto.SigninResp, error)
	// Refresh token
	RefreshToken(context.Context, *pbtypes.String) (*dto.SigninResp, error)
	// Ping
	Ping(context.Context, *pbtypes.Empty) (*pbtypes.Empty, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Signup(ctx context.Context, req *dto.SignupReq) (*pbtypes.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedAuthServer) Signin(ctx context.Context, req *dto.SigninReq) (*dto.SigninResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signin not implemented")
}
func (*UnimplementedAuthServer) SigninGoogle(ctx context.Context, req *pbtypes.String) (*dto.SigninResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigninGoogle not implemented")
}
func (*UnimplementedAuthServer) RefreshToken(ctx context.Context, req *pbtypes.String) (*dto.SigninResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedAuthServer) Ping(ctx context.Context, req *pbtypes.Empty) (*pbtypes.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.SignupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Signup(ctx, req.(*dto.SignupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.SigninReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Signin(ctx, req.(*dto.SigninReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SigninGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pbtypes.String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SigninGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/SigninGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SigninGoogle(ctx, req.(*pbtypes.String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pbtypes.String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshToken(ctx, req.(*pbtypes.String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pbtypes.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Ping(ctx, req.(*pbtypes.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Auth_Signup_Handler,
		},
		{
			MethodName: "Signin",
			Handler:    _Auth_Signin_Handler,
		},
		{
			MethodName: "SigninGoogle",
			Handler:    _Auth_SigninGoogle_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Auth_RefreshToken_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Auth_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/auth/grpc/auth.proto",
}
