// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/user/dto/invitation.proto

package dto

import (
	fmt "fmt"
	user "github.com/elojah/trax/internal/user"
	_ "github.com/elojah/trax/pkg/gogoproto"
	paginate "github.com/elojah/trax/pkg/paginate"
	github_com_elojah_trax_pkg_ulid "github.com/elojah/trax/pkg/ulid"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type InvitationView struct {
	Invitation user.Invitation `protobuf:"bytes,1,opt,name=Invitation,proto3" json:"Invitation"`
	RoleSample []user.Role     `protobuf:"bytes,2,rep,name=RoleSample,proto3" json:"RoleSample"`
	RoleCount  uint64          `protobuf:"varint,3,opt,name=RoleCount,proto3" json:"RoleCount,omitempty"`
}

func (m *InvitationView) Reset()      { *m = InvitationView{} }
func (*InvitationView) ProtoMessage() {}
func (*InvitationView) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a299ab25b4df04f, []int{0}
}
func (m *InvitationView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InvitationView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InvitationView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InvitationView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationView.Merge(m, src)
}
func (m *InvitationView) XXX_Size() int {
	return m.Size()
}
func (m *InvitationView) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationView.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationView proto.InternalMessageInfo

type CreateInvitationReq struct {
	Email   string                               `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	GroupID github_com_elojah_trax_pkg_ulid.ID   `protobuf:"bytes,2,opt,name=GroupID,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"GroupID"`
	RoleIDs []github_com_elojah_trax_pkg_ulid.ID `protobuf:"bytes,3,rep,name=RoleIDs,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"RoleIDs"`
}

func (m *CreateInvitationReq) Reset()      { *m = CreateInvitationReq{} }
func (*CreateInvitationReq) ProtoMessage() {}
func (*CreateInvitationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a299ab25b4df04f, []int{1}
}
func (m *CreateInvitationReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateInvitationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateInvitationReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateInvitationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInvitationReq.Merge(m, src)
}
func (m *CreateInvitationReq) XXX_Size() int {
	return m.Size()
}
func (m *CreateInvitationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInvitationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInvitationReq proto.InternalMessageInfo

type ListInvitationReq struct {
	Paginate *paginate.Paginate                   `protobuf:"bytes,1,opt,name=Paginate,proto3" json:"Paginate,omitempty"`
	Search   string                               `protobuf:"bytes,2,opt,name=Search,proto3" json:"Search,omitempty"`
	OwnGroup bool                                 `protobuf:"varint,3,opt,name=OwnGroup,proto3" json:"OwnGroup,omitempty"`
	IDs      []github_com_elojah_trax_pkg_ulid.ID `protobuf:"bytes,4,rep,name=IDs,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"IDs"`
	GroupIDs []github_com_elojah_trax_pkg_ulid.ID `protobuf:"bytes,5,rep,name=GroupIDs,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"GroupIDs"`
}

func (m *ListInvitationReq) Reset()      { *m = ListInvitationReq{} }
func (*ListInvitationReq) ProtoMessage() {}
func (*ListInvitationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a299ab25b4df04f, []int{2}
}
func (m *ListInvitationReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListInvitationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListInvitationReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListInvitationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInvitationReq.Merge(m, src)
}
func (m *ListInvitationReq) XXX_Size() int {
	return m.Size()
}
func (m *ListInvitationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInvitationReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListInvitationReq proto.InternalMessageInfo

type ListInvitationResp struct {
	Invitations []InvitationView `protobuf:"bytes,1,rep,name=Invitations,proto3" json:"Invitations"`
	Total       uint64           `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (m *ListInvitationResp) Reset()      { *m = ListInvitationResp{} }
func (*ListInvitationResp) ProtoMessage() {}
func (*ListInvitationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a299ab25b4df04f, []int{3}
}
func (m *ListInvitationResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListInvitationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListInvitationResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListInvitationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInvitationResp.Merge(m, src)
}
func (m *ListInvitationResp) XXX_Size() int {
	return m.Size()
}
func (m *ListInvitationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInvitationResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListInvitationResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InvitationView)(nil), "dto.InvitationView")
	golang_proto.RegisterType((*InvitationView)(nil), "dto.InvitationView")
	proto.RegisterType((*CreateInvitationReq)(nil), "dto.CreateInvitationReq")
	golang_proto.RegisterType((*CreateInvitationReq)(nil), "dto.CreateInvitationReq")
	proto.RegisterType((*ListInvitationReq)(nil), "dto.ListInvitationReq")
	golang_proto.RegisterType((*ListInvitationReq)(nil), "dto.ListInvitationReq")
	proto.RegisterType((*ListInvitationResp)(nil), "dto.ListInvitationResp")
	golang_proto.RegisterType((*ListInvitationResp)(nil), "dto.ListInvitationResp")
}

func init() {
	proto.RegisterFile("internal/user/dto/invitation.proto", fileDescriptor_6a299ab25b4df04f)
}
func init() {
	golang_proto.RegisterFile("internal/user/dto/invitation.proto", fileDescriptor_6a299ab25b4df04f)
}

var fileDescriptor_6a299ab25b4df04f = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xf6, 0xc5, 0x69, 0x49, 0x2e, 0x08, 0xc1, 0x15, 0x21, 0x2b, 0xa0, 0xd7, 0xc8, 0x53, 0xc4,
	0x60, 0xa3, 0x82, 0x58, 0x60, 0x4a, 0x03, 0x28, 0x12, 0x12, 0xe8, 0x8a, 0x18, 0xd8, 0xae, 0xcd,
	0xc9, 0x39, 0x70, 0x7c, 0xc6, 0x3e, 0x53, 0x46, 0x24, 0xfe, 0x00, 0x23, 0x3f, 0x81, 0x7f, 0x00,
	0x63, 0xc7, 0x8c, 0x19, 0x2b, 0x86, 0x0a, 0x3b, 0x0b, 0x63, 0x47, 0x46, 0x74, 0x17, 0xc7, 0x6e,
	0x8a, 0x18, 0xb2, 0xdd, 0xfb, 0xde, 0xfb, 0xbe, 0x7b, 0xef, 0xbb, 0x77, 0xd8, 0x15, 0x91, 0xe2,
	0x49, 0xc4, 0x42, 0x3f, 0x4b, 0x79, 0xe2, 0x8f, 0x95, 0xf4, 0x45, 0xf4, 0x41, 0x28, 0xa6, 0x84,
	0x8c, 0xbc, 0x38, 0x91, 0x4a, 0x12, 0x7b, 0xac, 0x64, 0xd7, 0x89, 0xdf, 0x05, 0x7e, 0x20, 0x03,
	0x69, 0x30, 0x73, 0x5a, 0xa6, 0xbb, 0xb7, 0x75, 0x26, 0x66, 0x81, 0x88, 0x98, 0xe2, 0xd5, 0xa1,
	0x4c, 0xc2, 0xba, 0xfe, 0x65, 0xed, 0xae, 0xb3, 0x9e, 0x4f, 0x64, 0x58, 0x32, 0xdd, 0xaf, 0x08,
	0x5f, 0x1b, 0x55, 0xe5, 0xaf, 0x05, 0x3f, 0x26, 0x0f, 0x31, 0xae, 0x11, 0x07, 0xf5, 0x50, 0xbf,
	0xb3, 0x77, 0xdd, 0xd3, 0x44, 0xaf, 0xc6, 0x07, 0xcd, 0xd9, 0xd9, 0xae, 0x45, 0x2f, 0x54, 0x92,
	0x7b, 0x18, 0x53, 0x19, 0xf2, 0x03, 0x36, 0x8d, 0x43, 0xee, 0x34, 0x7a, 0x76, 0xbf, 0xb3, 0x87,
	0x97, 0x3c, 0x8d, 0xaf, 0x18, 0x75, 0x0d, 0xb9, 0x83, 0xdb, 0x3a, 0xda, 0x97, 0x59, 0xa4, 0x1c,
	0xbb, 0x87, 0xfa, 0x4d, 0x5a, 0x03, 0xee, 0x77, 0x84, 0x77, 0xf6, 0x13, 0xce, 0x14, 0xaf, 0x2f,
	0xa1, 0xfc, 0x3d, 0xb9, 0x89, 0xb7, 0x9e, 0x4c, 0x99, 0x08, 0x4d, 0x6b, 0x6d, 0xba, 0x0c, 0xc8,
	0x10, 0x5f, 0x79, 0x96, 0xc8, 0x2c, 0x1e, 0x0d, 0x9d, 0x46, 0x0f, 0xf5, 0xaf, 0x0e, 0xee, 0xea,
	0xeb, 0x7e, 0x9e, 0xed, 0xba, 0x81, 0x50, 0x93, 0xec, 0xd0, 0x3b, 0x92, 0x53, 0x9f, 0x87, 0xf2,
	0x2d, 0x9b, 0xf8, 0x2a, 0x61, 0x1f, 0x7d, 0xed, 0x67, 0x16, 0x8a, 0xb1, 0x37, 0x1a, 0xd2, 0x15,
	0x55, 0xab, 0xe8, 0x06, 0x46, 0xc3, 0xd4, 0xb1, 0x7b, 0xf6, 0xa6, 0x2a, 0x25, 0xd5, 0xfd, 0xdc,
	0xc0, 0x37, 0x9e, 0x8b, 0x54, 0xad, 0xf7, 0xfd, 0x00, 0xb7, 0x5e, 0x96, 0xcf, 0x56, 0xba, 0x4a,
	0xbc, 0xea, 0x1d, 0x57, 0x19, 0xe3, 0x12, 0xa2, 0x55, 0x25, 0xb9, 0x85, 0xb7, 0x0f, 0x38, 0x4b,
	0x8e, 0x26, 0x66, 0xac, 0x36, 0x2d, 0x23, 0xd2, 0xc5, 0xad, 0x17, 0xc7, 0x91, 0xe9, 0xdb, 0x58,
	0xd7, 0xa2, 0x55, 0x4c, 0x1e, 0x63, 0x5b, 0x4f, 0xd0, 0xdc, 0x78, 0x02, 0x4d, 0x23, 0x4f, 0x71,
	0xab, 0xb4, 0x23, 0x75, 0xb6, 0x36, 0x96, 0xa8, 0xb8, 0x6e, 0x80, 0xc9, 0x65, 0x13, 0xd2, 0x98,
	0x3c, 0xc2, 0x9d, 0x1a, 0x49, 0x1d, 0x64, 0xd6, 0x64, 0xc7, 0x1b, 0x2b, 0xe9, 0xad, 0xef, 0x61,
	0xb9, 0x2f, 0x17, 0xab, 0xf5, 0xd3, 0xbf, 0x92, 0x8a, 0x85, 0xc6, 0x8b, 0x26, 0x5d, 0x06, 0x83,
	0x64, 0x96, 0x83, 0x35, 0xcf, 0xc1, 0x3a, 0xcd, 0xc1, 0x3a, 0xcf, 0x01, 0xfd, 0xc9, 0x01, 0x7d,
	0x2a, 0x00, 0x7d, 0x2b, 0x00, 0xfd, 0x28, 0x00, 0x9d, 0x14, 0x80, 0x66, 0x05, 0xa0, 0x79, 0x01,
	0xe8, 0x57, 0x01, 0xe8, 0x77, 0x01, 0xd6, 0x79, 0x01, 0xe8, 0xcb, 0x02, 0xac, 0x93, 0x05, 0xa0,
	0xf9, 0x02, 0xac, 0xd3, 0x05, 0x58, 0x6f, 0xfa, 0xff, 0x19, 0xf0, 0x9f, 0xef, 0x7b, 0xb8, 0x6d,
	0xbe, 0xcf, 0xfd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0xec, 0x0a, 0xb1, 0xda, 0x03, 0x00,
	0x00,
}

func (this *InvitationView) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InvitationView)
	if !ok {
		that2, ok := that.(InvitationView)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Invitation.Equal(&that1.Invitation) {
		return false
	}
	if len(this.RoleSample) != len(that1.RoleSample) {
		return false
	}
	for i := range this.RoleSample {
		if !this.RoleSample[i].Equal(&that1.RoleSample[i]) {
			return false
		}
	}
	if this.RoleCount != that1.RoleCount {
		return false
	}
	return true
}
func (this *CreateInvitationReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateInvitationReq)
	if !ok {
		that2, ok := that.(CreateInvitationReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Email != that1.Email {
		return false
	}
	if !this.GroupID.Equal(that1.GroupID) {
		return false
	}
	if len(this.RoleIDs) != len(that1.RoleIDs) {
		return false
	}
	for i := range this.RoleIDs {
		if !this.RoleIDs[i].Equal(that1.RoleIDs[i]) {
			return false
		}
	}
	return true
}
func (this *ListInvitationReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListInvitationReq)
	if !ok {
		that2, ok := that.(ListInvitationReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Paginate.Equal(that1.Paginate) {
		return false
	}
	if this.Search != that1.Search {
		return false
	}
	if this.OwnGroup != that1.OwnGroup {
		return false
	}
	if len(this.IDs) != len(that1.IDs) {
		return false
	}
	for i := range this.IDs {
		if !this.IDs[i].Equal(that1.IDs[i]) {
			return false
		}
	}
	if len(this.GroupIDs) != len(that1.GroupIDs) {
		return false
	}
	for i := range this.GroupIDs {
		if !this.GroupIDs[i].Equal(that1.GroupIDs[i]) {
			return false
		}
	}
	return true
}
func (this *ListInvitationResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListInvitationResp)
	if !ok {
		that2, ok := that.(ListInvitationResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Invitations) != len(that1.Invitations) {
		return false
	}
	for i := range this.Invitations {
		if !this.Invitations[i].Equal(&that1.Invitations[i]) {
			return false
		}
	}
	if this.Total != that1.Total {
		return false
	}
	return true
}
func (this *InvitationView) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&dto.InvitationView{")
	s = append(s, "Invitation: "+strings.Replace(this.Invitation.GoString(), `&`, ``, 1)+",\n")
	if this.RoleSample != nil {
		vs := make([]user.Role, len(this.RoleSample))
		for i := range vs {
			vs[i] = this.RoleSample[i]
		}
		s = append(s, "RoleSample: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "RoleCount: "+fmt.Sprintf("%#v", this.RoleCount)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateInvitationReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&dto.CreateInvitationReq{")
	s = append(s, "Email: "+fmt.Sprintf("%#v", this.Email)+",\n")
	s = append(s, "GroupID: "+fmt.Sprintf("%#v", this.GroupID)+",\n")
	s = append(s, "RoleIDs: "+fmt.Sprintf("%#v", this.RoleIDs)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListInvitationReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&dto.ListInvitationReq{")
	if this.Paginate != nil {
		s = append(s, "Paginate: "+fmt.Sprintf("%#v", this.Paginate)+",\n")
	}
	s = append(s, "Search: "+fmt.Sprintf("%#v", this.Search)+",\n")
	s = append(s, "OwnGroup: "+fmt.Sprintf("%#v", this.OwnGroup)+",\n")
	s = append(s, "IDs: "+fmt.Sprintf("%#v", this.IDs)+",\n")
	s = append(s, "GroupIDs: "+fmt.Sprintf("%#v", this.GroupIDs)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListInvitationResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dto.ListInvitationResp{")
	if this.Invitations != nil {
		vs := make([]InvitationView, len(this.Invitations))
		for i := range vs {
			vs[i] = this.Invitations[i]
		}
		s = append(s, "Invitations: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "Total: "+fmt.Sprintf("%#v", this.Total)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringInvitation(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *InvitationView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InvitationView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InvitationView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RoleCount != 0 {
		i = encodeVarintInvitation(dAtA, i, uint64(m.RoleCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RoleSample) > 0 {
		for iNdEx := len(m.RoleSample) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoleSample[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInvitation(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Invitation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInvitation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CreateInvitationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateInvitationReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateInvitationReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoleIDs) > 0 {
		for iNdEx := len(m.RoleIDs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.RoleIDs[iNdEx].Size()
				i -= size
				if _, err := m.RoleIDs[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintInvitation(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.GroupID.Size()
		i -= size
		if _, err := m.GroupID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInvitation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintInvitation(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListInvitationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListInvitationReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListInvitationReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GroupIDs) > 0 {
		for iNdEx := len(m.GroupIDs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.GroupIDs[iNdEx].Size()
				i -= size
				if _, err := m.GroupIDs[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintInvitation(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.IDs) > 0 {
		for iNdEx := len(m.IDs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.IDs[iNdEx].Size()
				i -= size
				if _, err := m.IDs[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintInvitation(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.OwnGroup {
		i--
		if m.OwnGroup {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Search) > 0 {
		i -= len(m.Search)
		copy(dAtA[i:], m.Search)
		i = encodeVarintInvitation(dAtA, i, uint64(len(m.Search)))
		i--
		dAtA[i] = 0x12
	}
	if m.Paginate != nil {
		{
			size, err := m.Paginate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInvitation(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListInvitationResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListInvitationResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListInvitationResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintInvitation(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Invitations) > 0 {
		for iNdEx := len(m.Invitations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Invitations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInvitation(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintInvitation(dAtA []byte, offset int, v uint64) int {
	offset -= sovInvitation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedInvitationView(r randyInvitation, easy bool) *InvitationView {
	this := &InvitationView{}
	v1 := user.NewPopulatedInvitation(r, easy)
	this.Invitation = *v1
	if r.Intn(5) != 0 {
		v2 := r.Intn(5)
		this.RoleSample = make([]user.Role, v2)
		for i := 0; i < v2; i++ {
			v3 := user.NewPopulatedRole(r, easy)
			this.RoleSample[i] = *v3
		}
	}
	this.RoleCount = uint64(uint64(r.Uint32()))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCreateInvitationReq(r randyInvitation, easy bool) *CreateInvitationReq {
	this := &CreateInvitationReq{}
	this.Email = string(randStringInvitation(r))
	v4 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
	this.GroupID = *v4
	v5 := r.Intn(10)
	this.RoleIDs = make([]github_com_elojah_trax_pkg_ulid.ID, v5)
	for i := 0; i < v5; i++ {
		v6 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
		this.RoleIDs[i] = *v6
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedListInvitationReq(r randyInvitation, easy bool) *ListInvitationReq {
	this := &ListInvitationReq{}
	if r.Intn(5) != 0 {
		this.Paginate = paginate.NewPopulatedPaginate(r, easy)
	}
	this.Search = string(randStringInvitation(r))
	this.OwnGroup = bool(bool(r.Intn(2) == 0))
	v7 := r.Intn(10)
	this.IDs = make([]github_com_elojah_trax_pkg_ulid.ID, v7)
	for i := 0; i < v7; i++ {
		v8 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
		this.IDs[i] = *v8
	}
	v9 := r.Intn(10)
	this.GroupIDs = make([]github_com_elojah_trax_pkg_ulid.ID, v9)
	for i := 0; i < v9; i++ {
		v10 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
		this.GroupIDs[i] = *v10
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedListInvitationResp(r randyInvitation, easy bool) *ListInvitationResp {
	this := &ListInvitationResp{}
	if r.Intn(5) != 0 {
		v11 := r.Intn(5)
		this.Invitations = make([]InvitationView, v11)
		for i := 0; i < v11; i++ {
			v12 := NewPopulatedInvitationView(r, easy)
			this.Invitations[i] = *v12
		}
	}
	this.Total = uint64(uint64(r.Uint32()))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyInvitation interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneInvitation(r randyInvitation) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringInvitation(r randyInvitation) string {
	v13 := r.Intn(100)
	tmps := make([]rune, v13)
	for i := 0; i < v13; i++ {
		tmps[i] = randUTF8RuneInvitation(r)
	}
	return string(tmps)
}
func randUnrecognizedInvitation(r randyInvitation, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldInvitation(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldInvitation(dAtA []byte, r randyInvitation, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		v14 := r.Int63()
		if r.Intn(2) == 0 {
			v14 *= -1
		}
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(v14))
	case 1:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateInvitation(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *InvitationView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Invitation.Size()
	n += 1 + l + sovInvitation(uint64(l))
	if len(m.RoleSample) > 0 {
		for _, e := range m.RoleSample {
			l = e.Size()
			n += 1 + l + sovInvitation(uint64(l))
		}
	}
	if m.RoleCount != 0 {
		n += 1 + sovInvitation(uint64(m.RoleCount))
	}
	return n
}

func (m *CreateInvitationReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovInvitation(uint64(l))
	}
	l = m.GroupID.Size()
	n += 1 + l + sovInvitation(uint64(l))
	if len(m.RoleIDs) > 0 {
		for _, e := range m.RoleIDs {
			l = e.Size()
			n += 1 + l + sovInvitation(uint64(l))
		}
	}
	return n
}

func (m *ListInvitationReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Paginate != nil {
		l = m.Paginate.Size()
		n += 1 + l + sovInvitation(uint64(l))
	}
	l = len(m.Search)
	if l > 0 {
		n += 1 + l + sovInvitation(uint64(l))
	}
	if m.OwnGroup {
		n += 2
	}
	if len(m.IDs) > 0 {
		for _, e := range m.IDs {
			l = e.Size()
			n += 1 + l + sovInvitation(uint64(l))
		}
	}
	if len(m.GroupIDs) > 0 {
		for _, e := range m.GroupIDs {
			l = e.Size()
			n += 1 + l + sovInvitation(uint64(l))
		}
	}
	return n
}

func (m *ListInvitationResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Invitations) > 0 {
		for _, e := range m.Invitations {
			l = e.Size()
			n += 1 + l + sovInvitation(uint64(l))
		}
	}
	if m.Total != 0 {
		n += 1 + sovInvitation(uint64(m.Total))
	}
	return n
}

func sovInvitation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInvitation(x uint64) (n int) {
	return sovInvitation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *InvitationView) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForRoleSample := "[]Role{"
	for _, f := range this.RoleSample {
		repeatedStringForRoleSample += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForRoleSample += "}"
	s := strings.Join([]string{`&InvitationView{`,
		`Invitation:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Invitation), "Invitation", "user.Invitation", 1), `&`, ``, 1) + `,`,
		`RoleSample:` + repeatedStringForRoleSample + `,`,
		`RoleCount:` + fmt.Sprintf("%v", this.RoleCount) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateInvitationReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateInvitationReq{`,
		`Email:` + fmt.Sprintf("%v", this.Email) + `,`,
		`GroupID:` + fmt.Sprintf("%v", this.GroupID) + `,`,
		`RoleIDs:` + fmt.Sprintf("%v", this.RoleIDs) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListInvitationReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListInvitationReq{`,
		`Paginate:` + strings.Replace(fmt.Sprintf("%v", this.Paginate), "Paginate", "paginate.Paginate", 1) + `,`,
		`Search:` + fmt.Sprintf("%v", this.Search) + `,`,
		`OwnGroup:` + fmt.Sprintf("%v", this.OwnGroup) + `,`,
		`IDs:` + fmt.Sprintf("%v", this.IDs) + `,`,
		`GroupIDs:` + fmt.Sprintf("%v", this.GroupIDs) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListInvitationResp) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForInvitations := "[]InvitationView{"
	for _, f := range this.Invitations {
		repeatedStringForInvitations += strings.Replace(strings.Replace(f.String(), "InvitationView", "InvitationView", 1), `&`, ``, 1) + ","
	}
	repeatedStringForInvitations += "}"
	s := strings.Join([]string{`&ListInvitationResp{`,
		`Invitations:` + repeatedStringForInvitations + `,`,
		`Total:` + fmt.Sprintf("%v", this.Total) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringInvitation(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *InvitationView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InvitationView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InvitationView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Invitation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleSample", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoleSample = append(m.RoleSample, user.Role{})
			if err := m.RoleSample[len(m.RoleSample)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleCount", wireType)
			}
			m.RoleCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoleCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInvitation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInvitation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateInvitationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateInvitationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateInvitationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleIDs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_elojah_trax_pkg_ulid.ID
			m.RoleIDs = append(m.RoleIDs, v)
			if err := m.RoleIDs[len(m.RoleIDs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvitation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInvitation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListInvitationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListInvitationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListInvitationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paginate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Paginate == nil {
				m.Paginate = &paginate.Paginate{}
			}
			if err := m.Paginate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Search", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Search = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnGroup", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OwnGroup = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IDs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_elojah_trax_pkg_ulid.ID
			m.IDs = append(m.IDs, v)
			if err := m.IDs[len(m.IDs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupIDs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_elojah_trax_pkg_ulid.ID
			m.GroupIDs = append(m.GroupIDs, v)
			if err := m.GroupIDs[len(m.GroupIDs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInvitation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInvitation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListInvitationResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListInvitationResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListInvitationResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invitations = append(m.Invitations, InvitationView{})
			if err := m.Invitations[len(m.Invitations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInvitation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInvitation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInvitation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInvitation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInvitation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInvitation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInvitation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInvitation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInvitation = fmt.Errorf("proto: unexpected end of group")
)
