// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/user/invitation.proto

package user

import (
	fmt "fmt"
	_ "github.com/elojah/trax/pkg/gogoproto"
	github_com_elojah_trax_pkg_ulid "github.com/elojah/trax/pkg/ulid"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Invitation struct {
	ID        github_com_elojah_trax_pkg_ulid.ID `protobuf:"bytes,1,opt,name=ID,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"ID"`
	Email     string                             `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	CreatedAt int64                              `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt int64                              `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (m *Invitation) Reset()      { *m = Invitation{} }
func (*Invitation) ProtoMessage() {}
func (*Invitation) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fd147e4ea70b51, []int{0}
}
func (m *Invitation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Invitation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Invitation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Invitation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invitation.Merge(m, src)
}
func (m *Invitation) XXX_Size() int {
	return m.Size()
}
func (m *Invitation) XXX_DiscardUnknown() {
	xxx_messageInfo_Invitation.DiscardUnknown(m)
}

var xxx_messageInfo_Invitation proto.InternalMessageInfo

type InvitationRole struct {
	InvitationID github_com_elojah_trax_pkg_ulid.ID `protobuf:"bytes,1,opt,name=InvitationID,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"InvitationID"`
	RoleID       github_com_elojah_trax_pkg_ulid.ID `protobuf:"bytes,2,opt,name=RoleID,proto3,customtype=github.com/elojah/trax/pkg/ulid.ID" json:"RoleID"`
	CreatedAt    int64                              `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt    int64                              `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (m *InvitationRole) Reset()      { *m = InvitationRole{} }
func (*InvitationRole) ProtoMessage() {}
func (*InvitationRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fd147e4ea70b51, []int{1}
}
func (m *InvitationRole) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InvitationRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InvitationRole.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InvitationRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationRole.Merge(m, src)
}
func (m *InvitationRole) XXX_Size() int {
	return m.Size()
}
func (m *InvitationRole) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationRole.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationRole proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Invitation)(nil), "user.Invitation")
	golang_proto.RegisterType((*Invitation)(nil), "user.Invitation")
	proto.RegisterType((*InvitationRole)(nil), "user.InvitationRole")
	golang_proto.RegisterType((*InvitationRole)(nil), "user.InvitationRole")
}

func init() { proto.RegisterFile("internal/user/invitation.proto", fileDescriptor_69fd147e4ea70b51) }
func init() {
	golang_proto.RegisterFile("internal/user/invitation.proto", fileDescriptor_69fd147e4ea70b51)
}

var fileDescriptor_69fd147e4ea70b51 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0xef, 0x01, 0x92, 0x70, 0x21, 0x0e, 0x17, 0x87, 0xc6, 0x98, 0x07, 0x21, 0x0e, 0xc4,
	0x81, 0x1b, 0xdc, 0xdc, 0xc4, 0x3a, 0x74, 0x71, 0x68, 0xe2, 0xe2, 0x76, 0xc8, 0xa5, 0x9c, 0x96,
	0x1e, 0xa9, 0x87, 0x71, 0xf4, 0x4f, 0x70, 0xf6, 0x2f, 0xf0, 0x4f, 0x70, 0x64, 0x64, 0x64, 0x24,
	0x0e, 0x84, 0x5e, 0x17, 0x47, 0x46, 0x47, 0xd3, 0x42, 0x68, 0x18, 0x1c, 0xd4, 0xed, 0xee, 0xf7,
	0xe5, 0xfb, 0xf2, 0xbd, 0xbc, 0x47, 0x51, 0x45, 0x46, 0xc6, 0x91, 0x08, 0xf9, 0xf8, 0x41, 0xc6,
	0x5c, 0x45, 0x8f, 0xca, 0x08, 0xa3, 0x74, 0xd4, 0x19, 0xc5, 0xda, 0x68, 0x56, 0xc9, 0xf0, 0xa1,
	0x33, 0xba, 0x0f, 0x78, 0xa0, 0x03, 0x9d, 0xc3, 0xfc, 0xb5, 0xd6, 0x5b, 0xaf, 0x40, 0xa9, 0xb7,
	0x35, 0xb1, 0x33, 0x5a, 0xf2, 0x5c, 0x07, 0x9a, 0xd0, 0xae, 0x77, 0x4f, 0xa6, 0x8b, 0x06, 0xf9,
	0x58, 0x34, 0x5a, 0x81, 0x32, 0x83, 0x71, 0xaf, 0x73, 0xab, 0x87, 0x5c, 0x86, 0xfa, 0x4e, 0x0c,
	0xb8, 0x89, 0xc5, 0x13, 0xcf, 0x32, 0xc7, 0xa1, 0xea, 0x77, 0x3c, 0xd7, 0x2f, 0x79, 0x2e, 0x3b,
	0xa0, 0x7b, 0x97, 0x43, 0xa1, 0x42, 0xa7, 0xd4, 0x84, 0x76, 0xcd, 0x5f, 0x7f, 0xd8, 0x11, 0xad,
	0x5d, 0xc4, 0x52, 0x18, 0xd9, 0x3f, 0x37, 0x4e, 0xb9, 0x09, 0xed, 0xb2, 0x5f, 0x80, 0x4c, 0xbd,
	0x1e, 0xf5, 0x37, 0x6a, 0x65, 0xad, 0x6e, 0x41, 0x6b, 0x09, 0x74, 0xbf, 0x28, 0xe7, 0xeb, 0x50,
	0xb2, 0x2b, 0x5a, 0x2f, 0xc8, 0x9f, 0xaa, 0xee, 0xf8, 0x59, 0x97, 0x56, 0xb3, 0x5c, 0xcf, 0xcd,
	0x5b, 0xff, 0x2e, 0x69, 0xe3, 0xfc, 0xcf, 0x88, 0xdd, 0x68, 0x9a, 0x20, 0x99, 0x25, 0x48, 0xe6,
	0x09, 0x92, 0x55, 0x82, 0xf0, 0x95, 0x20, 0x3c, 0x5b, 0x84, 0x37, 0x8b, 0xf0, 0x6e, 0x11, 0x26,
	0x16, 0x61, 0x6a, 0x11, 0x66, 0x16, 0x61, 0x69, 0x11, 0x3e, 0x2d, 0x92, 0x95, 0x45, 0x78, 0x49,
	0x91, 0x4c, 0x52, 0x84, 0x59, 0x8a, 0x64, 0x9e, 0x22, 0xb9, 0x39, 0xfe, 0xa1, 0xf1, 0xce, 0x81,
	0xf4, 0xaa, 0xf9, 0xda, 0x4f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xa5, 0x14, 0x11, 0x38,
	0x02, 0x00, 0x00,
}

func (this *Invitation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Invitation)
	if !ok {
		that2, ok := that.(Invitation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(that1.ID) {
		return false
	}
	if this.Email != that1.Email {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if this.UpdatedAt != that1.UpdatedAt {
		return false
	}
	return true
}
func (this *InvitationRole) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*InvitationRole)
	if !ok {
		that2, ok := that.(InvitationRole)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.InvitationID.Equal(that1.InvitationID) {
		return false
	}
	if !this.RoleID.Equal(that1.RoleID) {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if this.UpdatedAt != that1.UpdatedAt {
		return false
	}
	return true
}
func (this *Invitation) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&user.Invitation{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Email: "+fmt.Sprintf("%#v", this.Email)+",\n")
	s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	s = append(s, "UpdatedAt: "+fmt.Sprintf("%#v", this.UpdatedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *InvitationRole) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&user.InvitationRole{")
	s = append(s, "InvitationID: "+fmt.Sprintf("%#v", this.InvitationID)+",\n")
	s = append(s, "RoleID: "+fmt.Sprintf("%#v", this.RoleID)+",\n")
	s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	s = append(s, "UpdatedAt: "+fmt.Sprintf("%#v", this.UpdatedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringInvitation(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Invitation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Invitation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Invitation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintInvitation(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.CreatedAt != 0 {
		i = encodeVarintInvitation(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintInvitation(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.ID.Size()
		i -= size
		if _, err := m.ID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInvitation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *InvitationRole) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InvitationRole) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InvitationRole) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintInvitation(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.CreatedAt != 0 {
		i = encodeVarintInvitation(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.RoleID.Size()
		i -= size
		if _, err := m.RoleID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInvitation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.InvitationID.Size()
		i -= size
		if _, err := m.InvitationID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintInvitation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintInvitation(dAtA []byte, offset int, v uint64) int {
	offset -= sovInvitation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedInvitation(r randyInvitation, easy bool) *Invitation {
	this := &Invitation{}
	v1 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
	this.ID = *v1
	this.Email = string(randStringInvitation(r))
	this.CreatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CreatedAt *= -1
	}
	this.UpdatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.UpdatedAt *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedInvitationRole(r randyInvitation, easy bool) *InvitationRole {
	this := &InvitationRole{}
	v2 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
	this.InvitationID = *v2
	v3 := github_com_elojah_trax_pkg_ulid.NewPopulatedID(r)
	this.RoleID = *v3
	this.CreatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CreatedAt *= -1
	}
	this.UpdatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.UpdatedAt *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyInvitation interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneInvitation(r randyInvitation) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringInvitation(r randyInvitation) string {
	v4 := r.Intn(100)
	tmps := make([]rune, v4)
	for i := 0; i < v4; i++ {
		tmps[i] = randUTF8RuneInvitation(r)
	}
	return string(tmps)
}
func randUnrecognizedInvitation(r randyInvitation, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldInvitation(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldInvitation(dAtA []byte, r randyInvitation, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		v5 := r.Int63()
		if r.Intn(2) == 0 {
			v5 *= -1
		}
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(v5))
	case 1:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateInvitation(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateInvitation(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Invitation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovInvitation(uint64(l))
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovInvitation(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovInvitation(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovInvitation(uint64(m.UpdatedAt))
	}
	return n
}

func (m *InvitationRole) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.InvitationID.Size()
	n += 1 + l + sovInvitation(uint64(l))
	l = m.RoleID.Size()
	n += 1 + l + sovInvitation(uint64(l))
	if m.CreatedAt != 0 {
		n += 1 + sovInvitation(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovInvitation(uint64(m.UpdatedAt))
	}
	return n
}

func sovInvitation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInvitation(x uint64) (n int) {
	return sovInvitation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Invitation) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Invitation{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Email:` + fmt.Sprintf("%v", this.Email) + `,`,
		`CreatedAt:` + fmt.Sprintf("%v", this.CreatedAt) + `,`,
		`UpdatedAt:` + fmt.Sprintf("%v", this.UpdatedAt) + `,`,
		`}`,
	}, "")
	return s
}
func (this *InvitationRole) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&InvitationRole{`,
		`InvitationID:` + fmt.Sprintf("%v", this.InvitationID) + `,`,
		`RoleID:` + fmt.Sprintf("%v", this.RoleID) + `,`,
		`CreatedAt:` + fmt.Sprintf("%v", this.CreatedAt) + `,`,
		`UpdatedAt:` + fmt.Sprintf("%v", this.UpdatedAt) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringInvitation(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Invitation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Invitation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Invitation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInvitation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInvitation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InvitationRole) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InvitationRole: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InvitationRole: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvitationID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InvitationID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthInvitation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthInvitation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RoleID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInvitation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInvitation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInvitation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInvitation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInvitation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInvitation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInvitation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInvitation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInvitation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInvitation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInvitation = fmt.Errorf("proto: unexpected end of group")
)
