// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/elojah/trax/cmd/api/grpc/api.proto

package grpc

import (
	context "context"
	fmt "fmt"
	user "github.com/elojah/trax/internal/user"
	dto "github.com/elojah/trax/internal/user/dto"
	_ "github.com/elojah/trax/pkg/gogoproto"
	pbtypes "github.com/elojah/trax/pkg/pbtypes"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("github.com/elojah/trax/cmd/api/grpc/api.proto", fileDescriptor_e44be87dd4a64048)
}
func init() {
	golang_proto.RegisterFile("github.com/elojah/trax/cmd/api/grpc/api.proto", fileDescriptor_e44be87dd4a64048)
}

var fileDescriptor_e44be87dd4a64048 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0x7d, 0xa2, 0x2a, 0x70, 0x44, 0x01, 0xae, 0xc0, 0x90, 0xe1, 0x46, 0x10, 0x03, 0x3e,
	0x68, 0x55, 0x09, 0x89, 0xa9, 0x94, 0x22, 0x2a, 0x31, 0x44, 0x95, 0xf2, 0x01, 0x9c, 0xe4, 0x95,
	0x73, 0x60, 0xfb, 0x0e, 0xdf, 0x05, 0xd1, 0x8d, 0x8f, 0xc0, 0xc7, 0xe0, 0x23, 0x30, 0x76, 0xec,
	0x98, 0xb1, 0x23, 0x76, 0x84, 0xc4, 0xd8, 0x91, 0x11, 0xdd, 0x9d, 0xd3, 0xb3, 0x9d, 0xa4, 0x4a,
	0x97, 0xc8, 0xcf, 0xe3, 0xe7, 0x77, 0xf7, 0xfe, 0x71, 0xf0, 0x8b, 0x98, 0xeb, 0xc9, 0x74, 0x18,
	0x8e, 0x44, 0xca, 0x20, 0x11, 0x9f, 0xa2, 0x09, 0xd3, 0x79, 0xf4, 0x8d, 0x8d, 0xd2, 0x31, 0x8b,
	0x24, 0x67, 0x71, 0x2e, 0x47, 0xe6, 0x21, 0x94, 0xb9, 0xd0, 0x82, 0x6c, 0x19, 0xdd, 0x63, 0x6b,
	0x20, 0xf9, 0x39, 0x66, 0xb1, 0x88, 0x85, 0xcd, 0xda, 0x27, 0x87, 0xf5, 0xc2, 0x6b, 0x00, 0x39,
	0xd4, 0xa7, 0x12, 0x14, 0x83, 0x54, 0xea, 0xd3, 0x2a, 0xff, 0x6a, 0x4d, 0x9e, 0x67, 0x1a, 0xf2,
	0x2c, 0x4a, 0xd8, 0x54, 0x41, 0xce, 0x20, 0xd3, 0xfc, 0x0a, 0x61, 0x1b, 0x21, 0xe6, 0xe7, 0x46,
	0x77, 0x8c, 0x92, 0x88, 0xa7, 0xaa, 0x42, 0xf6, 0x37, 0x42, 0xc6, 0x5a, 0x34, 0x4b, 0xdb, 0xdb,
	0x18, 0xcb, 0x45, 0x02, 0x37, 0x86, 0x7c, 0x4f, 0xbb, 0x7f, 0xb6, 0xf1, 0xad, 0x83, 0xfe, 0x31,
	0x79, 0x8a, 0xb7, 0xfa, 0x3c, 0x8b, 0x49, 0x37, 0xac, 0xa6, 0x1b, 0x1e, 0x99, 0xe9, 0xf6, 0x5a,
	0x9a, 0x30, 0x7c, 0xe7, 0x23, 0x57, 0x7a, 0xa0, 0x20, 0x27, 0x0f, 0xc2, 0xb1, 0x16, 0xe1, 0x42,
	0x9e, 0xc0, 0x97, 0xde, 0xc3, 0x96, 0xa3, 0x24, 0x79, 0x86, 0xef, 0xbe, 0x07, 0x3d, 0x9a, 0x58,
	0xc2, 0xbd, 0xbf, 0xd2, 0x06, 0xb9, 0x1d, 0xda, 0x6a, 0x06, 0xe4, 0x39, 0xc6, 0x03, 0x39, 0x8e,
	0x34, 0xd8, 0x24, 0xb1, 0x49, 0x6f, 0xb4, 0xa3, 0xc7, 0xd9, 0x57, 0xde, 0x88, 0x7a, 0xa3, 0x11,
	0x0d, 0xf1, 0x3d, 0x7b, 0xdd, 0xa1, 0xdd, 0xca, 0x52, 0x7b, 0xf7, 0x5d, 0xce, 0xbe, 0x3d, 0x98,
	0xea, 0x09, 0xd9, 0xc7, 0xd8, 0x94, 0x7f, 0x64, 0xb7, 0x51, 0x1d, 0xed, 0x0d, 0x73, 0xf4, 0xce,
	0x92, 0xa7, 0x24, 0x79, 0x59, 0x5d, 0x53, 0x71, 0x3b, 0xbe, 0x4f, 0x0f, 0x76, 0xdc, 0x5d, 0x55,
	0x64, 0x17, 0x77, 0x0e, 0x73, 0x88, 0x34, 0x54, 0xfa, 0x91, 0x45, 0xea, 0xd6, 0x4a, 0xc6, 0x4d,
	0xa4, 0xc1, 0xd4, 0xad, 0x65, 0xe6, 0x0d, 0xee, 0xbc, 0x83, 0x04, 0x5a, 0x4c, 0xdd, 0x32, 0xcc,
	0xe3, 0x15, 0xae, 0x92, 0x8b, 0x6d, 0x9f, 0x88, 0x04, 0x6a, 0xdb, 0x36, 0xb2, 0xb9, 0x6d, 0xe7,
	0x28, 0x69, 0xc6, 0xe7, 0x5a, 0xb0, 0x08, 0xa9, 0xf5, 0xb4, 0x80, 0xdc, 0x68, 0x8c, 0xea, 0x43,
	0x9e, 0x72, 0xa5, 0xb8, 0xc8, 0x0c, 0xe6, 0xba, 0xa8, 0x61, 0xde, 0xb8, 0x0e, 0x73, 0x25, 0xd7,
	0x30, 0x6f, 0xac, 0xc5, 0x5e, 0xe3, 0xae, 0xaf, 0xc9, 0x7e, 0x42, 0x4f, 0x5a, 0x85, 0x2e, 0x3e,
	0xa3, 0xae, 0xab, 0xc4, 0x28, 0x91, 0x80, 0x32, 0xa4, 0x3f, 0xbf, 0x46, 0x36, 0xcd, 0x15, 0xe4,
	0xdb, 0x0f, 0xe7, 0x05, 0x0d, 0x66, 0x05, 0x0d, 0x2e, 0x0a, 0x1a, 0x5c, 0x16, 0x14, 0xfd, 0x2b,
	0x28, 0xfa, 0x5e, 0x52, 0xf4, 0xb3, 0xa4, 0xe8, 0x57, 0x49, 0xd1, 0x59, 0x49, 0xd1, 0x79, 0x49,
	0xd1, 0xac, 0xa4, 0xe8, 0x77, 0x49, 0xd1, 0xdf, 0x92, 0x06, 0x97, 0x25, 0x45, 0x3f, 0xe6, 0x34,
	0x38, 0x9b, 0x53, 0x34, 0x9b, 0xd3, 0xe0, 0x62, 0x4e, 0x83, 0xe1, 0xb6, 0xfd, 0xe3, 0xee, 0xfd,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xac, 0xec, 0x1e, 0x88, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// Ping
	Ping(ctx context.Context, in *pbtypes.Empty, opts ...grpc.CallOption) (*pbtypes.Empty, error)
	// User
	ListUser(ctx context.Context, in *dto.ListUserReq, opts ...grpc.CallOption) (*dto.ListUserResp, error)
	FetchUser(ctx context.Context, in *dto.FetchUserReq, opts ...grpc.CallOption) (*user.U, error)
	UpdateUser(ctx context.Context, in *dto.UpdateUserReq, opts ...grpc.CallOption) (*user.U, error)
	InviteUser(ctx context.Context, in *dto.InviteUserReq, opts ...grpc.CallOption) (*user.U, error)
	// Claims
	FetchClaims(ctx context.Context, in *pbtypes.Empty, opts ...grpc.CallOption) (*user.ClaimAuth, error)
	// Entity
	ListEntity(ctx context.Context, in *dto.ListEntityReq, opts ...grpc.CallOption) (*dto.ListEntityResp, error)
	FetchEntity(ctx context.Context, in *dto.FetchEntityReq, opts ...grpc.CallOption) (*user.Entity, error)
	CreateEntity(ctx context.Context, in *dto.CreateEntityReq, opts ...grpc.CallOption) (*user.Entity, error)
	UpdateEntity(ctx context.Context, in *dto.UpdateEntityReq, opts ...grpc.CallOption) (*user.Entity, error)
	DeleteEntity(ctx context.Context, in *dto.DeleteEntityReq, opts ...grpc.CallOption) (*dto.DeleteEntityResp, error)
	// Roles
	ListRole(ctx context.Context, in *dto.ListRoleReq, opts ...grpc.CallOption) (*dto.ListRoleResp, error)
	CreateRole(ctx context.Context, in *dto.CreateRoleReq, opts ...grpc.CallOption) (*dto.RolePermission, error)
	UpdateRole(ctx context.Context, in *dto.UpdateRoleReq, opts ...grpc.CallOption) (*dto.RolePermission, error)
	DeleteRole(ctx context.Context, in *dto.DeleteRoleReq, opts ...grpc.CallOption) (*dto.RolePermission, error)
	// Roles user
	CreateRoleUser(ctx context.Context, in *dto.CreateRoleUserReq, opts ...grpc.CallOption) (*dto.UserRoles, error)
	DeleteRoleUser(ctx context.Context, in *dto.DeleteRoleUserReq, opts ...grpc.CallOption) (*dto.UserRoles, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Ping(ctx context.Context, in *pbtypes.Empty, opts ...grpc.CallOption) (*pbtypes.Empty, error) {
	out := new(pbtypes.Empty)
	err := c.cc.Invoke(ctx, "/grpc.API/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListUser(ctx context.Context, in *dto.ListUserReq, opts ...grpc.CallOption) (*dto.ListUserResp, error) {
	out := new(dto.ListUserResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) FetchUser(ctx context.Context, in *dto.FetchUserReq, opts ...grpc.CallOption) (*user.U, error) {
	out := new(user.U)
	err := c.cc.Invoke(ctx, "/grpc.API/FetchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateUser(ctx context.Context, in *dto.UpdateUserReq, opts ...grpc.CallOption) (*user.U, error) {
	out := new(user.U)
	err := c.cc.Invoke(ctx, "/grpc.API/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) InviteUser(ctx context.Context, in *dto.InviteUserReq, opts ...grpc.CallOption) (*user.U, error) {
	out := new(user.U)
	err := c.cc.Invoke(ctx, "/grpc.API/InviteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) FetchClaims(ctx context.Context, in *pbtypes.Empty, opts ...grpc.CallOption) (*user.ClaimAuth, error) {
	out := new(user.ClaimAuth)
	err := c.cc.Invoke(ctx, "/grpc.API/FetchClaims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListEntity(ctx context.Context, in *dto.ListEntityReq, opts ...grpc.CallOption) (*dto.ListEntityResp, error) {
	out := new(dto.ListEntityResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) FetchEntity(ctx context.Context, in *dto.FetchEntityReq, opts ...grpc.CallOption) (*user.Entity, error) {
	out := new(user.Entity)
	err := c.cc.Invoke(ctx, "/grpc.API/FetchEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateEntity(ctx context.Context, in *dto.CreateEntityReq, opts ...grpc.CallOption) (*user.Entity, error) {
	out := new(user.Entity)
	err := c.cc.Invoke(ctx, "/grpc.API/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateEntity(ctx context.Context, in *dto.UpdateEntityReq, opts ...grpc.CallOption) (*user.Entity, error) {
	out := new(user.Entity)
	err := c.cc.Invoke(ctx, "/grpc.API/UpdateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteEntity(ctx context.Context, in *dto.DeleteEntityReq, opts ...grpc.CallOption) (*dto.DeleteEntityResp, error) {
	out := new(dto.DeleteEntityResp)
	err := c.cc.Invoke(ctx, "/grpc.API/DeleteEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListRole(ctx context.Context, in *dto.ListRoleReq, opts ...grpc.CallOption) (*dto.ListRoleResp, error) {
	out := new(dto.ListRoleResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateRole(ctx context.Context, in *dto.CreateRoleReq, opts ...grpc.CallOption) (*dto.RolePermission, error) {
	out := new(dto.RolePermission)
	err := c.cc.Invoke(ctx, "/grpc.API/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateRole(ctx context.Context, in *dto.UpdateRoleReq, opts ...grpc.CallOption) (*dto.RolePermission, error) {
	out := new(dto.RolePermission)
	err := c.cc.Invoke(ctx, "/grpc.API/UpdateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteRole(ctx context.Context, in *dto.DeleteRoleReq, opts ...grpc.CallOption) (*dto.RolePermission, error) {
	out := new(dto.RolePermission)
	err := c.cc.Invoke(ctx, "/grpc.API/DeleteRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateRoleUser(ctx context.Context, in *dto.CreateRoleUserReq, opts ...grpc.CallOption) (*dto.UserRoles, error) {
	out := new(dto.UserRoles)
	err := c.cc.Invoke(ctx, "/grpc.API/CreateRoleUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteRoleUser(ctx context.Context, in *dto.DeleteRoleUserReq, opts ...grpc.CallOption) (*dto.UserRoles, error) {
	out := new(dto.UserRoles)
	err := c.cc.Invoke(ctx, "/grpc.API/DeleteRoleUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// Ping
	Ping(context.Context, *pbtypes.Empty) (*pbtypes.Empty, error)
	// User
	ListUser(context.Context, *dto.ListUserReq) (*dto.ListUserResp, error)
	FetchUser(context.Context, *dto.FetchUserReq) (*user.U, error)
	UpdateUser(context.Context, *dto.UpdateUserReq) (*user.U, error)
	InviteUser(context.Context, *dto.InviteUserReq) (*user.U, error)
	// Claims
	FetchClaims(context.Context, *pbtypes.Empty) (*user.ClaimAuth, error)
	// Entity
	ListEntity(context.Context, *dto.ListEntityReq) (*dto.ListEntityResp, error)
	FetchEntity(context.Context, *dto.FetchEntityReq) (*user.Entity, error)
	CreateEntity(context.Context, *dto.CreateEntityReq) (*user.Entity, error)
	UpdateEntity(context.Context, *dto.UpdateEntityReq) (*user.Entity, error)
	DeleteEntity(context.Context, *dto.DeleteEntityReq) (*dto.DeleteEntityResp, error)
	// Roles
	ListRole(context.Context, *dto.ListRoleReq) (*dto.ListRoleResp, error)
	CreateRole(context.Context, *dto.CreateRoleReq) (*dto.RolePermission, error)
	UpdateRole(context.Context, *dto.UpdateRoleReq) (*dto.RolePermission, error)
	DeleteRole(context.Context, *dto.DeleteRoleReq) (*dto.RolePermission, error)
	// Roles user
	CreateRoleUser(context.Context, *dto.CreateRoleUserReq) (*dto.UserRoles, error)
	DeleteRoleUser(context.Context, *dto.DeleteRoleUserReq) (*dto.UserRoles, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) Ping(ctx context.Context, req *pbtypes.Empty) (*pbtypes.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedAPIServer) ListUser(ctx context.Context, req *dto.ListUserReq) (*dto.ListUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (*UnimplementedAPIServer) FetchUser(ctx context.Context, req *dto.FetchUserReq) (*user.U, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchUser not implemented")
}
func (*UnimplementedAPIServer) UpdateUser(ctx context.Context, req *dto.UpdateUserReq) (*user.U, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedAPIServer) InviteUser(ctx context.Context, req *dto.InviteUserReq) (*user.U, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteUser not implemented")
}
func (*UnimplementedAPIServer) FetchClaims(ctx context.Context, req *pbtypes.Empty) (*user.ClaimAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchClaims not implemented")
}
func (*UnimplementedAPIServer) ListEntity(ctx context.Context, req *dto.ListEntityReq) (*dto.ListEntityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntity not implemented")
}
func (*UnimplementedAPIServer) FetchEntity(ctx context.Context, req *dto.FetchEntityReq) (*user.Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchEntity not implemented")
}
func (*UnimplementedAPIServer) CreateEntity(ctx context.Context, req *dto.CreateEntityReq) (*user.Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (*UnimplementedAPIServer) UpdateEntity(ctx context.Context, req *dto.UpdateEntityReq) (*user.Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntity not implemented")
}
func (*UnimplementedAPIServer) DeleteEntity(ctx context.Context, req *dto.DeleteEntityReq) (*dto.DeleteEntityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntity not implemented")
}
func (*UnimplementedAPIServer) ListRole(ctx context.Context, req *dto.ListRoleReq) (*dto.ListRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRole not implemented")
}
func (*UnimplementedAPIServer) CreateRole(ctx context.Context, req *dto.CreateRoleReq) (*dto.RolePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (*UnimplementedAPIServer) UpdateRole(ctx context.Context, req *dto.UpdateRoleReq) (*dto.RolePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (*UnimplementedAPIServer) DeleteRole(ctx context.Context, req *dto.DeleteRoleReq) (*dto.RolePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (*UnimplementedAPIServer) CreateRoleUser(ctx context.Context, req *dto.CreateRoleUserReq) (*dto.UserRoles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoleUser not implemented")
}
func (*UnimplementedAPIServer) DeleteRoleUser(ctx context.Context, req *dto.DeleteRoleUserReq) (*dto.UserRoles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoleUser not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pbtypes.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Ping(ctx, req.(*pbtypes.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListUser(ctx, req.(*dto.ListUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_FetchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.FetchUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).FetchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/FetchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).FetchUser(ctx, req.(*dto.FetchUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateUser(ctx, req.(*dto.UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.InviteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/InviteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).InviteUser(ctx, req.(*dto.InviteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_FetchClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pbtypes.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).FetchClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/FetchClaims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).FetchClaims(ctx, req.(*pbtypes.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListEntity(ctx, req.(*dto.ListEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_FetchEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.FetchEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).FetchEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/FetchEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).FetchEntity(ctx, req.(*dto.FetchEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.CreateEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateEntity(ctx, req.(*dto.CreateEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UpdateEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/UpdateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateEntity(ctx, req.(*dto.UpdateEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.DeleteEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/DeleteEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteEntity(ctx, req.(*dto.DeleteEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListRole(ctx, req.(*dto.ListRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateRole(ctx, req.(*dto.CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateRole(ctx, req.(*dto.UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.DeleteRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteRole(ctx, req.(*dto.DeleteRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateRoleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.CreateRoleUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateRoleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreateRoleUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateRoleUser(ctx, req.(*dto.CreateRoleUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteRoleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.DeleteRoleUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteRoleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/DeleteRoleUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteRoleUser(ctx, req.(*dto.DeleteRoleUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _API_Ping_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _API_ListUser_Handler,
		},
		{
			MethodName: "FetchUser",
			Handler:    _API_FetchUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _API_UpdateUser_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _API_InviteUser_Handler,
		},
		{
			MethodName: "FetchClaims",
			Handler:    _API_FetchClaims_Handler,
		},
		{
			MethodName: "ListEntity",
			Handler:    _API_ListEntity_Handler,
		},
		{
			MethodName: "FetchEntity",
			Handler:    _API_FetchEntity_Handler,
		},
		{
			MethodName: "CreateEntity",
			Handler:    _API_CreateEntity_Handler,
		},
		{
			MethodName: "UpdateEntity",
			Handler:    _API_UpdateEntity_Handler,
		},
		{
			MethodName: "DeleteEntity",
			Handler:    _API_DeleteEntity_Handler,
		},
		{
			MethodName: "ListRole",
			Handler:    _API_ListRole_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _API_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _API_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _API_DeleteRole_Handler,
		},
		{
			MethodName: "CreateRoleUser",
			Handler:    _API_CreateRoleUser_Handler,
		},
		{
			MethodName: "DeleteRoleUser",
			Handler:    _API_DeleteRoleUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/elojah/trax/cmd/api/grpc/api.proto",
}
